import 'package:country_state_city/country_state_city.dart';

const OPENWEATHER_API_KEY = "bf4f6c40dc28c33876c0223f85341715";

List<String> cities = [
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Ahmedabad',
  'Chennai',
  'Kolkata',
  'Surat',
  'Pune',
  'Jaipur',
  'Lucknow',
  'Noida',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Pimpri-Chinchwad',
  'Patna',
  'Vadodara',

  //LowerCase
  'mumbai',
  'delhi',
  'bangalore',
  'hyderabad',
  'ahmedabad',
  'chennai',
  'kolkata',
  'surat',
  'pune',
  'jaipur',
  'lucknow',
  'noida',
  'kanpur',
  'nagpur',
  'indore',
  'thane',
  'bhopal',
  'visakhapatnam',
  'pimpri-Chinchwad',
  'patna',
  'vadodara',
];
